"""student model

Revision ID: e31b89dc19ca
Revises: 9381f815ff08
Create Date: 2024-01-24 05:33:47.146525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31b89dc19ca'
down_revision = '9381f815ff08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_no', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('state_of_origin', sa.String(length=70), nullable=True),
    sa.Column('lga_of_origin', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('course_of_study', sa.String(length=190), nullable=True),
    sa.Column('address', sa.String(length=190), nullable=True),
    sa.Column('means_of_id', sa.String(length=100), nullable=True),
    sa.Column('means_of_id_no', sa.String(length=100), nullable=True),
    sa.Column('means_of_id_upload', sa.String(length=191), nullable=True),
    sa.Column('employment_status', sa.String(length=100), nullable=True),
    sa.Column('level_of_education', sa.String(length=100), nullable=True),
    sa.Column('disabled', sa.String(length=5), nullable=True),
    sa.Column('disability_detail', sa.String(length=1000), nullable=True),
    sa.Column('emergency_full_name', sa.String(length=150), nullable=False),
    sa.Column('emergency_email', sa.String(length=100), nullable=False),
    sa.Column('emergency_phone_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_address', sa.String(length=150), nullable=False),
    sa.Column('guardian_first_name', sa.String(length=60), nullable=False),
    sa.Column('guardian_last_name', sa.String(length=60), nullable=False),
    sa.Column('guardian_email', sa.String(length=100), nullable=False),
    sa.Column('guardian_phone_number', sa.String(length=20), nullable=True),
    sa.Column('guardian_address', sa.String(length=191), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=False),
    sa.Column('headshot', sa.TEXT(), nullable=False),
    sa.Column('terms', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('means_of_id_no'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
